name: "Update image in manifest"
description: "This action will update docker image in manifest file and commit changes to repository"

inputs:
  manifest:
    description: "path to manifest file"
    required: true
  tag:
    description: "Image tag to deploy"
    required: true

runs:
  using: "composite"
  steps:

    - uses: actions/checkout@v4
      with:
        ref: refs/heads/main
        show-progress: false
        repository: theverytruestory/deployments
        ssh-key: ~/.ssh/id_ed25519
        sparse-checkout: k0s/apps
        path: deployments
        fetch-depth: 1


    - name: update image tag in manifest
      shell: bash
      run: |
        manifests=$(echo '${{ inputs.manifest }}' | sed ':a;N;$!ba;s/[\n\ \t]\+/ /g')
        for manifest in ${manifests}; do
          sed -i 's/\(image:.*${{ github.event.repository.name }}\):.*/\1:${{ inputs.tag }}/' ${manifest}
        done
        git diff -U0 --color=always || echo -e "git-diff exitcode $? \n${YEL}No changes in manifest${NC}"
#        for manifest in ${{ inputs.manifest }}; do
#          git add ${manifest}
#        done
#        git commit -m "${{ github.actor }}@${{ github.event.repository.name }}#${{ github.run_number }}: ${{ github.event.head_commit.message }}" || echo -e "git-commit exitcode $? \n${YEL}No changes in manifest${NC}"
      env:
        YEL: '\033[1;33m'
        NC: '\033[0m'
      working-directory: deployments/k0s/apps

#    - uses: ad-m/github-push-action@master
#      with:
#        branch: main
#        ssh: true
#        directory: deployments
#        repository: theverytruestory/deployments
#
