name: "Update flux image and deploy on kube"
description: "This action will update docker image id and deploy in on K8s"

inputs:
  manifest:
    description: "path to manifest file"
    required: true
  image_tag:
    description: "Image tag to deploy"
    required: true

outputs:
  describe:
    description: "kubectl describe"
    value: ${{ steps.set-output.outputs.KUBECTL_DESCRIBE }}

runs:
  using: "composite"
  steps:

    - name: checkout flux repo and set image tag '${{ inputs.image_tag }}' to manifest '${{ inputs.manifest }}'
      shell: bash
      id: flux
      env:
        GIT_SSH_COMMAND: 'ssh -i /tmp/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=no'
        GIT_PAGER: 'cat'
        MANIFEST: ${{ inputs.manifest }}
      run: |
        rm -rf ./flux
        git clone git@github.com:theverytruestory/flux.git flux
        cd flux
        sed -i '1,/image:.*/{s/\(image:[^:]*\):.*/\1:${{ inputs.image_tag }}/;}' ${{ inputs.manifest }}
        git diff -U0 --color=always
        git config user.name "GitHub Automation"
        git config user.email "GitHubActions@thetruestory.news"
        git add ${{ inputs.manifest }}
        git commit -a -m "from ${{ github.event.repository.name }} at ${{ inputs.image_tag }} (${{ env.branch }})" || true
        git push || true
        sleep 3
        CLUSTER=${MANIFEST:%%/*}
        aws eks update-kubeconfig --name $CLUSTER --region eu-north-1
        kubectl -n flux-system wait kustomization/flux-system --for=condition=ready --timeout=2m
        kubectl rollout status  -f ${MANIFEST}
        kubectl describe -f ${MANIFEST}

    - name: Set outputs
      id: set-output
      shell: bash
      run: |
        echo "KUBECTL_DESCRIBE<<EOF" >> $GITHUB_OUTPUT
        kubectl describe -f ${MANIFEST} >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT


