name: "Update flux image and deploy on kube"
description: "This action will update docker image id and deploy in on K8s"

inputs:
  cluster:
    description: "cluster to deploy"
    required: false
    default: "truestory"
  kubeconfig:
    description: "path to kubeconfig"
    required: false
    default: "~/.kube/kubeconfig"
  image_tag:
    description: "Image tag to deploy"
    required: true
    default: latest
  token:
    description: "token to access private repos"
    required: false

runs:
  using: "composite"
  steps:
    - name: prepare
      shell: bash
      run: |
        ls -la 
        ls -la /tmp/.ssh
        echo "ID_RSA<<EOF"    >> $GITHUB_ENV
        cat /tmp/.ssh/id_rsa  >> $GITHUB_ENV 
        echo "EOF"            >> $GITHUB_ENV
        rm -rf ./flux

    - name: "flux git"
      uses: actions/checkout@v4
      with:
        ssh-key: ID_RSA
        repository: theverytruestory/flux
        path: flux
        sparse-checkout: ''
        ssh-strict: ''

    - name: Copy manifest to flux repo
      shell: bash
      run: |
        cp ${{ github.workspace }}/manifest.yaml fluxcd/clusters/${{ inputs.cluster }}/${{ inputs.env }}/${{ env.app_name }}.yaml
        git config user.name "Fluxcd Automation"
        git config user.email "fluxcd@Phoenix365.tech"
        git add clusters/${{ inputs.cluster }}/${{ inputs.env }}/${{ env.app_name }}.yaml
        git commit -a -m "from ${{ github.event.repository.name }} at ${{ inputs.image_tag }} (${{ env.branch }})"
        git push

    - name: Deploy on EKS
      shell: bash
      run: |
        aws eks update-kubeconfig --name ${{ inputs.cluster }} --kubeconfig ${{ inputs.kubeconfig }}
        export KUBECONFIG=${{ inputs.kubeconfig }}
        kubectl rollout status deployment ${{ env.app_name }} -n ${{ inputs.env }} --timeout=120s
        kubectl describe deployment ${{ env.app_name }} -n ${{ inputs.env }}