name: "Update flux image and deploy on kube"
description: "This action will update docker image id and deploy in on K8s"

inputs:
  manifest:
    description: "path to manifest file"
    required: true
  image_tag:
    description: "Image tag to deploy"
    required: true

runs:
  using: "composite"
  steps:

    - name: flux
      shell: bash
      run: |
        export GIT_SSH_COMMAND='ssh -i /tmp/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=no'
        export GIT_PAGER='cat'
        rm -rf ./flux
        git clone git@github.com:theverytruestory/flux.git flux
        cd flux
        sed -i '1,/image:.*/{s/\(image:[^:]*\):.*/\1:${{ env.image_tag }}/;}' ${{ inputs.manifest }}
        git diff -U0 --color=always || true
        git config user.name "GitHub Automation"
        git config user.email "GitHubActions@thetruestory.news"
        git add ${{ inputs.manifest }}
        git commit -a -m "from ${{ github.event.repository.name }} at ${{ inputs.image_tag }} (${{ env.branch }})"
        git push

#    - name: Deploy on EKS
#      shell: bash
#      run: |
#        aws eks update-kubeconfig --name ${{ inputs.cluster }} --kubeconfig ${{ inputs.kubeconfig }}
#        export KUBECONFIG=${{ inputs.kubeconfig }}
#        kubectl rollout status deployment ${{ env.app_name }} -n ${{ inputs.env }} --timeout=120s
#        kubectl describe deployment ${{ env.app_name }} -n ${{ inputs.env }}