name: "ArgoCD set image (JS example)"
description: "Example of how this would look in JavaScript"

inputs:
  registry:
    description: "Docker registry"
    required: false
    default: "registry.truestory.work"
  repo:
    description: "Repository name"
    required: false
    default: ""
  tag:
    description: "Docker image tag"
    required: true
  argoapp:
    description: "ArgoCD application name"
    required: true
  kustomization_path:
    description: "Path to kustomization.yaml"
    required: false
    default: "kustomization.yaml"
  timeout:
    description: "Timeout for app stabilization"
    required: false
    default: "2m"

outputs:
  status:
    description: "Deployment status"

runs:
  using: 'node20'
  main: 'dist/index.js'  # Собранный файл (после npm run build)
  # или
  # main: 'index.js'     # Если коммитите node_modules