name: "Docker build and upload to ECR"
description: "This will build docker image and upload it to ECR"

inputs:
  docker_file:
    description: "Path to dockerfile"
    required: false
    default: "./Dockerfile"
outputs:
  image_url:
    description: "Image url"
    value: ${{ steps.set-output.outputs.image_url }}
  image_tag:
    description: "Image tag"
    value: ${{ steps.set-output.outputs.image_tag }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-north-1

    - name: Get or create ECR repository
      shell: bash
      run: >
        aws ecr describe-repositories --repository-names ${{ github.event.repository.name }}
        --query "repositories[0].repositoryUri" || aws ecr create-repository --repository-name ${{ github.event.repository.name }}

    - name: Get variables
      id: set-vars
      shell: bash
      run: |
        image_tag=$(git rev-parse --short HEAD)
        echo "image_tag=${image_tag}" >> $GITHUB_ENV
        ecr=648358337825.dkr.ecr.eu-north-1.amazonaws.com && echo "ecr=${ecr}" >> $GITHUB_ENV
        echo "image_url=${ecr}/${{ github.event.repository.name }}:${image_tag}" >> $GITHUB_ENV
        echo "ecr_password=$(aws ecr get-login-password)" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push ::notice::${{ env.image_url }}
      uses: docker/build-push-action@v6
      with:
        push: true
        file: ${{ inputs.docker_file }}
        tags:  ${{ env.image_url }}

    - name: Set outputs
      id: set-output
      shell: bash
      run: |
        echo "image_tag=${{ env.image_tag }}" >> $GITHUB_ENV
        echo "image_url=${{ env.image_url }}" >> $GITHUB_OUTPUT


