name: build custom runner

on:
  push:
    paths:
      - 'actions-runner-image/*'
      - '.github/workflows/build-runner-htz.yaml'
  workflow_dispatch:

env:
  REGISTRY: registry.htz.tsof.news:5000
  CONTEXT: actions-runner-image


jobs:

  prepare:
    runs-on: htz-k0s
    steps:

    - uses: actions/checkout@v4

    - name: set vars
      id: set-vars
      run: |
        echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "REPO="${{ env.REGISTRY }}/actions-runner-htz"" >> $GITHUB_ENV
        echo "DOCKER_BUILD_RECORD_UPLOAD=false"


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Import Registry CA
      run: echo "$ROOT_CA_PEM" > /tmp/root-ca.pem
      env:
        ROOT_CA_PEM: ${{ vars.ROOT_CA }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."registry.htz.tsof.news:5000"]
            ca=["/tmp/root-ca.pem"]

    - name: Build and push
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        context: ${{ env.CONTEXT }}
        push: true
        file: ${{ env.CONTEXT }}/Dockerfile
        tags: ${{ env.REPO }}:${{ env.TAG }},${{ env.REPO }}:latest
        cache-from: type=registry,ref=${{ env.REPO }}:buildcache
        cache-to: type=registry,ref=${{ env.REPO }}:buildcache,mode=max
