name: build custom runner

on:
  push:
    paths:
      - 'actions-runner-image/*'
      - '.github/workflows/build-runner-htz.yaml'
  workflow_dispatch:

env:
  REGISTRY: registry.htz.tsof.news
  CONTEXT: actions-runner-image


jobs:

  prepare:
    runs-on: standard
    steps:

    - uses: actions/checkout@v4

    - name: set vars
      id: set-vars
      run: |
        echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "REPO="${{ env.REGISTRY }}/actions-runner-htz"" >> $GITHUB_ENV

    - name: create version.json
      shell: bash
      run: git log -1 --pretty="${fmt}" | tee ${{ env.CONTEXT }}/version.json
      env:
        fmt: 'tformat:{%n"git commit": "%H",%n"git hash": "%h",%n"git author": "%an %ae",%n"git date": "%ai",%n"git subject": "%s",%n"git branch": "%D"%n}'


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Import Registry CA
      run: echo "$ROOT_CA_PEM" > ${{ env.CONTEXT }}/root-ca.pem
      env:
        ROOT_CA_PEM: ${{ vars.ROOT_CA }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."registry.truestory.work"]
            ca=["${{ env.CONTEXT }}/root-ca.pem"]
            mirrors = ["registry.htz.tsof.news"]

    - name: Docker login
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY }} -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

    - name: Build and push
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_RECORD_UPLOAD: false
      with:
        context: ${{ env.CONTEXT }}
        push: true
        file: ${{ env.CONTEXT }}/Dockerfile
        tags: ${{ env.REPO }}:${{ env.TAG }},${{ env.REPO }}:latest
        cache-from: type=registry,ref=${{ env.REPO }}:buildcache
        cache-to: type=registry,ref=${{ env.REPO }}:buildcache,mode=max
