name: build custom runner

on:
  push:
    paths:
      - 'actiopns-runner-image/*'
      - '.github/workflows/build-runner.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - test
        - staging
      tag:
        description: 'Image tag to deploy'
        required: false

env:
  cluster: truestory
  ecr: 648358337825.dkr.ecr.eu-north-1.amazonaws.com
  repository: custom-action-runner
  tag: ${{ github.event.inputs.tag || 'latest' }}
#  env: ${{ github.event.inputs.environment || 'dev' }}
#  KUBECONFIG: "~/.kube/kubeconfig"
#  AWS_DEFAULT_REGION: eu-central-1

jobs:

  prepare:
    runs-on: truestory-eks
    steps:

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install awscli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-north-1

    - name: Get or create ECR repository
      shell: bash
      run: >
        aws ecr describe-repositories --repository-names ${{ env.repository }}
        --query "repositories[0].repositoryUri" || aws ecr create-repository --repository-name ${{ env.repository }}

    - name: Get variables
      id: set-vars
      shell: bash
      run: |
        ecr=648358337825.dkr.ecr.eu-north-1.amazonaws.com && echo "ecr=${ecr}" >> $GITHUB_ENV
        echo "image_url=${{ env.ecr }}/${{ env.repository }}:${{ env.tag }}" >> $GITHUB_ENV
        echo "ecr_password=$(aws ecr get-login-password)" >> $GITHUB_ENV

    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push ::notice::${{ env.image_url }}
      uses: docker/build-push-action@v6
      with:
        push: true
        file: actions-runner-image/Dockerfile
        tags:  ${{ env.image_url }}

    - name: Set outputs
      id: set-output
      shell: bash
      run: |
        echo "image_url=${{ env.image_url }}" >> $GITHUB_OUTPUT
