name: build custom runner

on:
  push:
    paths:
      - 'actions-runner-swarm/*'
      - '.github/workflows/build-runner-swarm.yaml'
  workflow_dispatch:

env:
  REGISTRY: registry.htz.tsof.news:5000

jobs:

  prepare:
    runs-on: swarm
    steps:

    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Import Registry CA
      run: echo "$ROOT_CA_PEM" > /tmp/root-ca.pem
      env:
        ROOT_CA_PEM: ${{ vars.ROOT_CA }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."registry.htz.tsof.news:5000"]
            ca=["/tmp/root-ca.pem"]

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        file: actions-runner-swarm/Dockerfile
        tags:  ${{ env.REGISTRY }}/github-myoung34-tsof:latest
