name: build custom runner

on:
  push:
    paths:
      - 'actions-runner-image/*'
      - '.github/workflows/build-runner-htz.yaml'
  workflow_dispatch:

env:
  REGISTRY: registry.htz.tsof.news:5000

jobs:

  prepare:
    runs-on: htz-k0s
    steps:

    - uses: actions/checkout@v4

    - name: set vars
      id: set-vars
      run: |
        echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "REPO_NAME="${{ env.REGISTRY }}/actions-runner-htz"" >> $GITHUB_ENV


    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Import Registry CA
      run: echo "$ROOT_CA_PEM" > /tmp/root-ca.pem
      env:
        ROOT_CA_PEM: ${{ vars.ROOT_CA }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."registry.htz.tsof.news:5000"]
            ca=["/tmp/root-ca.pem"]

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: actions-runner-swarm
        push: true
        file: actions-runner-image/Dockerfile
        tags:  ${{ env.REPO_NAME }}:${{ env.TAG }}
        cache-from: type=registry,ref=${{ env.REPO_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.REPO_NAME }}:buildcache,mode=max
